language: node_js
node_js:
- '6'
env:
  matrix:
  - CXX=g++-4.8
  global:
  - secure: jafgXlak8pS5iDRbF43c/flx4JkKoXl200oI4Pl/60jq2QKa9mb6kgLZainMkDGp7dDPcUiFvvr5sdYMsIeU8pClZjvDobu4UVSRKQqMbmUKIS7PxjDFAcRRMjKZvTZDe0G/l83I4eVWy1v64VwNs+CbM69PVsted8IKpwq2vbc=
  - secure: FzWkAQ8K1jUSc1m1sUu+CKQQgp7IruolAFaFUMgShYHIbxuJ3lLWUKKfM+PheX/UMoxPY+um2Ul/dYl5hOuw9qog08td1pF9FOkUYsH4UpDpegqMh6SopnwOPCfx2E7aZcoY44YrwngSNq8nDa4KvezSRYkCN6PD0USRqTckW6k=
  - secure: e/ikkmb6R1RuaZb4Vvg9BiKHnw/ESpfUnl1tMxweFdaPKqCBF0rb7so9+G2ud7PO+25ZMV+wErRSgumpur36Hdev/xDsxhCKahu9wmERkOWoG9Vnd2UzhoAZCH4IaA57Trf1gmuflVo5GPyuAiND5yJHHtPPrWw/ebjjJuSn8f0=
sudo: required
dist: trusty
addons:
  ssh_known_hosts: github.com
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
cache:
- apt
- directories:
  - node_modules
deploy:
  provider: script
  script: ".travis/deploy_prod.sh"
  skip_cleanup: true
before_install:
- openssl aes-256-cbc -K $encrypted_d7ef8710d4fd_key -iv $encrypted_d7ef8710d4fd_iv
  -in .travis/secrets.tar.enc -out .travis/secrets.tar -d
- tar xvf .travis/secrets.tar -C .travis/
- mkdir -p ~/.ssh
- cp .travis/known_hosts ~/.ssh/known_hosts
- chmod 600 ~/.ssh/known_hosts
- gem install octokit
- ".travis/set-commit-status.rb"
install:
- ".travis/install.sh"
after_success:
- ".travis/deploy_testing.sh"
