name: ansible-test

on:
  pull_request:
    types: [ opened, synchronize ]
    
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      # Rebuild Mumbot image
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          push: false # Don't push PRs
          tags: theta142/mumbot:latest
      
      # Not sure if needed  
      - uses: actions/checkout@v3
      
      - name: Install necessary Python packages on runner
        run: |
          pip3 install requests
          pip3 install docker
      
      - uses: cbpowell/ansible-playbook-docker-action@v1.5
        env:
          # Config
          GH_COMMIT_STATUS_TOKEN: ${{ secrets. GH_COMMIT_STATUS_TOKEN }}
          HUBOT_IRC_PASSWORD: ${{ secrets.HUBOT_IRC_PASSWORD }}
          HUBOT_DISCORDER_GUILD: ${{ secrets.HUBOT_DISCORDER_GUILD }}
          HUBOT_DISCORDER_TOKEN: ${{ secrets.HUBOT_DISCORDER_TOKEN }}
          HUBOT_GIPHY_API_KEY: ${{ secrets.HUBOT_GIPHY_API_KEY }}
          HUBOT_GOOGLE_CSE_ID: ${{ secrets.HUBOT_GOOGLE_CSE_ID }}
          HUBOT_GOOGLE_CSE_KEY: ${{ secrets.HUBOT_GOOGLE_CSE_KEY }}
        with:
          playbookName:     .ansible/deploy.yml
          inventoryFile:    .ansible/inventory_test.yml
          requirementsFile: .ansible/requirements.yml
          extraFile:        .ansible/test_vars.yml
          keyFile:          .ansible/id_mumbot.pem
          vaultPass:        ${{ secrets.KEYFILE_VAULT_PASS }}
          # verbosity: "vvv"
