name: ansible-deploy

on:
  # Triggers the workflow on push events but only for the master branch
  push:
    branches: [ master ]
    
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - uses: cbpowell/ansible-playbook-docker-action@4cc39a556f40415632037a578b88dc57fbab7101
        env:
          # Config
          HUBOT_IRC_PASSWORD: ${{ secrets.HUBOT_IRC_PASSWORD }}
          HUBOT_DISCORDER_GUILD: ${{ secrets.HUBOT_DISCORDER_GUILD }}
          HUBOT_DISCORDER_TOKEN: ${{ secrets.HUBOT_DISCORDER_TOKEN }}
          HUBOT_GIPHY_API_KEY: ${{ secrets.HUBOT_GIPHY_API_KEY }}
          HUBOT_GOOGLE_CSE_ID: ${{ secrets.HUBOT_GOOGLE_CSE_ID }}
          HUBOT_GOOGLE_CSE_KEY: ${{ secrets.HUBOT_GOOGLE_CSE_KEY }}
        with:
          playbookName:     .ansible/deploy.yml
          inventoryFile:    .ansible/inventory.yml
          requirementsFile: .ansible/requirements.yml
          keyFile:          .ansible/id_mumbot.pem
          vaultPass:        ${{ secrets.KEYFILE_VAULT_PASS }}
          # verbosity: "vvv"
